package com.eliux.catchthepig.logic;


import java.util.ArrayList;



class AINode {
	ArrayList<AINode> nodes; // Sons
	GameMove played; 	// Posible play
	GameBoard board; 		// Artificial AI (Generated by the controller)

	public AINode(GameBoard board, GameMove played) {
		super();
		this.board = board;
		this.played = played; 
		this.nodes = new ArrayList<AINode>();  
	}

	
	
	public GameMove getPlayed() {
		return played;
	}

	public void setPlayed(GameMove played) {
		this.played = played;
	}

	public ArrayList<AINode> getNodes() {
		return nodes;
	}

	public void setNodes(ArrayList<AINode> nodes) {
		this.nodes = nodes;
	}

}